/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.VitalSign;
import Business.Patient;
import javax.swing.JOptionPane;

/**
 *
 * @author SONY
 */
public class CreateVSJPanel extends javax.swing.JPanel {
private Patient pat;
    /**
     * Creates new form CreateVSJPanel
     */
    public CreateVSJPanel(Patient pat) {
        initComponents();
       
        this.pat = pat;
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblrespRate = new javax.swing.JLabel();
        lblheartRate = new javax.swing.JLabel();
        lblsysBP = new javax.swing.JLabel();
        lblwt = new javax.swing.JLabel();
        txtrespRate = new javax.swing.JTextField();
        txtsysBP = new javax.swing.JTextField();
        txtheartRate = new javax.swing.JTextField();
        txtwt = new javax.swing.JTextField();
        BtnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lblrespRate.setText("Respiratory Rate");

        lblheartRate.setText("Heart Rate");

        lblsysBP.setText("Systolic Blood Pressure");

        lblwt.setText("Weight in pounds");

        txtrespRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrespRateActionPerformed(evt);
            }
        });

        txtsysBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsysBPActionPerformed(evt);
            }
        });

        txtheartRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtheartRateActionPerformed(evt);
            }
        });

        txtwt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwtActionPerformed(evt);
            }
        });

        BtnSave.setText("SAVE");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei Light", 3, 18)); // NOI18N
        jLabel1.setText("Vital Sign Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsysBP)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblheartRate)
                                    .addComponent(lblwt)
                                    .addComponent(lblrespRate))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtwt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsysBP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtrespRate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtheartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblrespRate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrespRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblheartRate)
                    .addComponent(txtheartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsysBP)
                    .addComponent(txtsysBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblwt)
                    .addComponent(txtwt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnSave)
                .addContainerGap(277, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtrespRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrespRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrespRateActionPerformed

    private void txtsysBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsysBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsysBPActionPerformed

    private void txtheartRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtheartRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtheartRateActionPerformed

    private void txtwtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwtActionPerformed

    private void resetFields(){
    txtrespRate.setText("");
    txtheartRate.setText("");
    txtsysBP.setText("");
    txtwt.setText("");
    }
    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        try{
        if( pat.getPatientName()!= null
                && pat.getPatientID() != null
                && pat.getPrimaryDoctor()!= null 
                  && pat.getPrefPharmacy()!= null){
        
        int rrate = Integer.parseInt(txtrespRate.getText());
        int hrate = Integer.parseInt(txtheartRate.getText());
        int bp = Integer.parseInt(txtsysBP.getText());
        float wt= Float.parseFloat(txtwt.getText());
        
        if(rrate > 0 && hrate > 0 && bp >0 && wt > 0.0 ){
        VitalSign vs = pat.getvSHistory().addVitalSign();
        vs.setRespRate(rrate);
        vs.setHeartRate(hrate);
        vs.setBloodPressure(bp);
        vs.setWeight(wt);
        vs.getTimestamp();
        
        //Display success message
        JOptionPane.showMessageDialog(null, "Vital Sign added sucessfully" , "Add Success", JOptionPane.INFORMATION_MESSAGE);
        
        resetFields();
        }
        else{
         JOptionPane.showMessageDialog(null,"Enter a valid input", "Invalid Input", JOptionPane.INFORMATION_MESSAGE);
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please add patient first", "Invalid Start", JOptionPane.ERROR_MESSAGE);
        }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Only numbers accepted.Please enter valid values","Invalid input", JOptionPane.ERROR_MESSAGE);
        }
        
        
                  
        
    }//GEN-LAST:event_BtnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblheartRate;
    private javax.swing.JLabel lblrespRate;
    private javax.swing.JLabel lblsysBP;
    private javax.swing.JLabel lblwt;
    private javax.swing.JTextField txtheartRate;
    private javax.swing.JTextField txtrespRate;
    private javax.swing.JTextField txtsysBP;
    private javax.swing.JTextField txtwt;
    // End of variables declaration//GEN-END:variables
}
