/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import Business.Patient;
import Business.VitalSign;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SONY
 */
public class ViewVitalSignHistoryJPanel extends javax.swing.JPanel {
private Patient pat;
private VitalSign vs;
private String st;

    /**
     * Creates new form ViewVitalSignHistoryJPanel
     */
    public ViewVitalSignHistoryJPanel(Patient pat) {
        initComponents();
        this.pat = pat;
        patDetails();
        
        //call populate table method
        populateTable();
        
    }

    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        int rowCount = dtm.getRowCount();
        
        for(int i = rowCount-1; i>=0; i--){
            dtm.removeRow(i);
        }
        
        for(VitalSign vs : pat.getvSHistory().getVSHistory()){    
            Object[] row = new Object[2];
            row[0]=vs;
            row[1]=vs.getStatus(pat,vs);
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnViewDetails = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        lblresprate = new javax.swing.JLabel();
        lblhrate = new javax.swing.JLabel();
        lblbp = new javax.swing.JLabel();
        lblwt = new javax.swing.JLabel();
        lblts = new javax.swing.JLabel();
        TxtRespRate = new javax.swing.JTextField();
        txthrate = new javax.swing.JTextField();
        Txtbp = new javax.swing.JTextField();
        TxtWT = new javax.swing.JTextField();
        txtTimestamp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtPatName = new javax.swing.JTextField();
        TxtPatID = new javax.swing.JTextField();
        TxtAge = new javax.swing.JTextField();
        TxtpriDoc = new javax.swing.JTextField();
        TxtprefPharm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Timestamp", "Normal/ Abnormal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtnViewDetails.setText("View Details");
        BtnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewDetailsActionPerformed(evt);
            }
        });

        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        lblresprate.setText("Respiratory Rate");

        lblhrate.setText("Heart Rate");

        lblbp.setText("Blood Pressure");

        lblwt.setText("Weight in pounds");

        lblts.setText("Timestamp");

        TxtRespRate.setEditable(false);

        txthrate.setEditable(false);

        Txtbp.setEditable(false);
        Txtbp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtbpActionPerformed(evt);
            }
        });

        TxtWT.setEditable(false);

        txtTimestamp.setEditable(false);
        txtTimestamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimestampActionPerformed(evt);
            }
        });

        jLabel1.setText("Patient Name");

        jLabel2.setText("Patient ID");

        jLabel3.setText("Age");

        jLabel4.setText("Primary Doctor Name");

        jLabel5.setText("Preferred Pharmacy");

        TxtPatName.setEditable(false);

        TxtPatID.setEditable(false);
        TxtPatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPatIDActionPerformed(evt);
            }
        });

        TxtAge.setEditable(false);

        TxtpriDoc.setEditable(false);

        TxtprefPharm.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel6.setText("Vital Sign History for the Patient");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtpriDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtPatID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TxtPatName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblresprate)
                                            .addComponent(lblhrate)
                                            .addComponent(lblbp)
                                            .addComponent(lblwt)
                                            .addComponent(lblts)
                                            .addComponent(jLabel5))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TxtRespRate)
                                            .addComponent(txthrate)
                                            .addComponent(Txtbp)
                                            .addComponent(TxtWT)
                                            .addComponent(txtTimestamp, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                            .addComponent(TxtprefPharm)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(BtnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnViewDetails)
                    .addComponent(BtnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtPatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtPatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtpriDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtprefPharm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblresprate)
                            .addComponent(TxtRespRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblhrate))
                    .addComponent(txthrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbp)
                    .addComponent(Txtbp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblwt)
                    .addComponent(TxtWT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblts)
                    .addComponent(txtTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtbpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtbpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtbpActionPerformed

    private void txtTimestampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimestampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimestampActionPerformed

    private void BtnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        
        if(selectedRow>=0){
            VitalSign vs = (VitalSign)jTable1.getValueAt(selectedRow, 0);
            TxtRespRate.setText(String.valueOf(vs.getRespRate()));
            txthrate.setText(String.valueOf(vs.getHeartRate()));
            Txtbp.setText(String.valueOf(vs.getBloodPressure()));
            TxtWT.setText(String.valueOf(vs.getWeight()));
            txtTimestamp.setText(vs.getTimestamp());
            
        }
        else
            JOptionPane.showMessageDialog(null, "Please select a row first !", "Error Message", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BtnViewDetailsActionPerformed

    private void resetFields(){
    TxtRespRate.setText("");
    txthrate.setText("");
    Txtbp.setText("");
    TxtWT.setText("");
    TxtPatName.setText("");
    TxtPatID.setText("");
    TxtpriDoc.setText("");
    TxtprefPharm.setText("");
    TxtAge.setText("");
    txtTimestamp.setText("");
    
    }
    
    private void patDetails(){
        TxtPatName.setText(pat.getPatientName());
        TxtPatID.setText(pat.getPatientID());
        TxtAge.setText(String.valueOf(pat.getPatientAge()));
        TxtpriDoc.setText(pat.getPrimaryDoctor());
        TxtprefPharm.setText(pat.getPrefPharmacy());
        
    }
      
    
    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow(); 
        if(selectedRow>=0){
            int dialogOption = JOptionPane.showConfirmDialog(null, " Would you like to delete selected VitalSign?","" ,JOptionPane.YES_NO_OPTION);
            if(dialogOption == JOptionPane.YES_OPTION){
            VitalSign vs = (VitalSign)jTable1.getValueAt(selectedRow, 0);
             pat.getvSHistory().deleteVitalSign(vs);
            populateTable();
            resetFields();
            }
        }
        
        else
           JOptionPane.showMessageDialog(null, "Please select a row from table", "Warning", JOptionPane.WARNING_MESSAGE);
            
    
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void TxtPatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPatIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPatIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnViewDetails;
    private javax.swing.JTextField TxtAge;
    private javax.swing.JTextField TxtPatID;
    private javax.swing.JTextField TxtPatName;
    private javax.swing.JTextField TxtRespRate;
    private javax.swing.JTextField TxtWT;
    private javax.swing.JTextField Txtbp;
    private javax.swing.JTextField TxtprefPharm;
    private javax.swing.JTextField TxtpriDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblbp;
    private javax.swing.JLabel lblhrate;
    private javax.swing.JLabel lblresprate;
    private javax.swing.JLabel lblts;
    private javax.swing.JLabel lblwt;
    private javax.swing.JTextField txtTimestamp;
    private javax.swing.JTextField txthrate;
    // End of variables declaration//GEN-END:variables
}
