/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import business.Patient;
import business.PersonList;
import business.VitalSign;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author SONY
 */
public class ManagePatientWorkAreaJPanel1 extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private PersonList patientList;
    private Patient patient;
    private VitalSign vSH;
 

    /**
     * Creates new form CreatePersonJPanel
     */
    public ManagePatientWorkAreaJPanel1(JPanel upc,PersonList pList) {
        this.userProcessContainer = upc;
        this.patientList = pList;
        this.patient = patient;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCreatePatient = new javax.swing.JButton();
        BtnAddVS = new javax.swing.JButton();
        BtnMngVS = new javax.swing.JButton();

        BtnCreatePatient.setText("Create Patient");
        BtnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreatePatientActionPerformed(evt);
            }
        });

        BtnAddVS.setText("Add VitalSign");
        BtnAddVS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddVSActionPerformed(evt);
            }
        });

        BtnMngVS.setText("Manage VitalSign");
        BtnMngVS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMngVSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnMngVS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCreatePatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAddVS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(BtnCreatePatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAddVS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnMngVS)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreatePatientActionPerformed
        // TODO add your handling code here:
        CreatePatientJPanel1 cpjp= new CreatePatientJPanel1(userProcessContainer,patientList);
        userProcessContainer.add(cpjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_BtnCreatePatientActionPerformed

    private void BtnAddVSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddVSActionPerformed
        // TODO add your handling code here:
        CreateVSJPanel vsjp = new CreateVSJPanel(userProcessContainer,patientList);
        userProcessContainer.add(vsjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_BtnAddVSActionPerformed

    private void BtnMngVSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMngVSActionPerformed
        // TODO add your handling code here:
        ViewVitalSignHistoryJPanel vshjp = new ViewVitalSignHistoryJPanel(userProcessContainer,patientList);
        userProcessContainer.add(vshjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_BtnMngVSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddVS;
    private javax.swing.JButton BtnCreatePatient;
    private javax.swing.JButton BtnMngVS;
    // End of variables declaration//GEN-END:variables
}
