/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;
//import business.Patient;

import business.Person;
import business.PersonList;
import business.VitalSign;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SONY
 */
public class ViewVitalSignHistoryJPanel extends javax.swing.JPanel {

    private Person person;
    private VitalSign vs;
    private String st;
    private JPanel userProcessContainer;
    private PersonList personList;

    /**
     * Creates new form ViewVitalSignHistoryJPanel
     */
    public ViewVitalSignHistoryJPanel(JPanel userProcessContainer, PersonList pList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personList = pList;
        btnSave.setEnabled(false);

        for (Person p : personList.getPersonList()) {
            String pid = p.getPatient().getPatientID();
            if (pid == null) {
                return;
            } else {
                selectPatComboBox.addItem(p);
            }

        }
    }

    private void populateTable() {
        Person p = (Person) selectPatComboBox.getSelectedItem();

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int rowCount = dtm.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        for (VitalSign vs : p.getVitalSignHistory().getVSHistory()) {
            Object[] row = new Object[2];
            row[0] = vs;
            row[1] = vs.getStatus(p, vs);
            dtm.addRow(row);
        }

        TxtAge.setText(String.valueOf(p.getAge()));
        TxtPatID.setText(p.getPatient().getPatientID());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnViewDetails = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        lblresprate = new javax.swing.JLabel();
        lblhrate = new javax.swing.JLabel();
        lblbp = new javax.swing.JLabel();
        lblwt = new javax.swing.JLabel();
        lblts = new javax.swing.JLabel();
        TxtRespRate = new javax.swing.JTextField();
        txthrate = new javax.swing.JTextField();
        Txtbp = new javax.swing.JTextField();
        txtTimestamp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtPatID = new javax.swing.JTextField();
        TxtAge = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        selectPatComboBox = new javax.swing.JComboBox();
        btnGo = new javax.swing.JButton();
        txtWT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        jTable1.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Timestamp", "Normal/ Abnormal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtnViewDetails.setText("View Details");
        BtnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewDetailsActionPerformed(evt);
            }
        });

        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        lblresprate.setText("Respiratory Rate");

        lblhrate.setText("Heart Rate");

        lblbp.setText("Blood Pressure");

        lblwt.setText("Weight in pounds");

        lblts.setText("Timestamp");

        Txtbp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtbpActionPerformed(evt);
            }
        });

        txtTimestamp.setEditable(false);
        txtTimestamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimestampActionPerformed(evt);
            }
        });

        jLabel2.setText("Patient ID");

        jLabel3.setText("Age");

        TxtPatID.setEditable(false);
        TxtPatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPatIDActionPerformed(evt);
            }
        });

        TxtAge.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel6.setText("Vital Sign History for the Patient");

        selectPatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Patient from the list" }));
        selectPatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPatComboBoxActionPerformed(evt);
            }
        });

        btnGo.setText("GO");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        jButton1.setText("<< BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("SAVE CHANGES");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtPatID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblresprate)
                                        .addComponent(lblhrate)
                                        .addComponent(lblbp)
                                        .addComponent(lblwt)
                                        .addComponent(lblts))
                                    .addGap(70, 70, 70)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtRespRate)
                                        .addComponent(txthrate)
                                        .addComponent(Txtbp)
                                        .addComponent(txtTimestamp)
                                        .addComponent(txtWT, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectPatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnSave)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectPatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnViewDetails)
                    .addComponent(BtnDelete)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtPatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblresprate)
                            .addComponent(TxtRespRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblhrate))
                    .addComponent(txthrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbp)
                    .addComponent(Txtbp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblwt)
                    .addComponent(txtWT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblts)
                    .addComponent(txtTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtbpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtbpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtbpActionPerformed

    private void txtTimestampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimestampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimestampActionPerformed

    private void BtnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewDetailsActionPerformed
        // TODO add your handling code here:
        displayDetails();
        editPermission(false);

    }//GEN-LAST:event_BtnViewDetailsActionPerformed

    private void editPermission(Boolean s) {

        for (int i = 0; i < 8; i++) {
            TxtRespRate.setEditable(s);
            Txtbp.setEditable(s);
            txtWT.setEditable(s);
            txthrate.setEditable(s);

        }

    }

    private void displayDetails() {
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow >= 0) {
            VitalSign vs = (VitalSign) jTable1.getValueAt(selectedRow, 0);
            TxtRespRate.setText(String.valueOf(vs.getRespRate()));
            txthrate.setText(String.valueOf(vs.getHeartRate()));
            Txtbp.setText(String.valueOf(vs.getBloodPressure()));
            txtWT.setText(String.valueOf(vs.getWeight()));
            txtTimestamp.setText(vs.getTimestamp());

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row first !", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void resetFields() {
        TxtRespRate.setText("");
        txthrate.setText("");
        Txtbp.setText("");
        txtWT.setText("");

        txtTimestamp.setText("");

    }

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            int dialogOption = JOptionPane.showConfirmDialog(null, " Would you like to delete selected VitalSign?", "", JOptionPane.YES_NO_OPTION);
            if (dialogOption == JOptionPane.YES_OPTION) {
                Person person = (Person) selectPatComboBox.getSelectedItem();
                VitalSign vs = (VitalSign) jTable1.getValueAt(selectedRow, 0);
                person.getVitalSignHistory().deleteVitalSign(vs);
                populateTable();
                resetFields();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from table", "Warning", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void TxtPatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPatIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPatIDActionPerformed

    private void selectPatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPatComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_selectPatComboBoxActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnGoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        displayDetails();
        editPermission(true);
        btnSave.setEnabled(true);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            try {

                int rrate = Integer.parseInt(TxtRespRate.getText());
                int hrate = Integer.parseInt(txthrate.getText());
                int bp = Integer.parseInt(Txtbp.getText());
                float wt = Float.parseFloat(txtWT.getText());

                if (rrate > 0 && hrate > 0 && bp > 0 && wt > 0.0) {
                    // System.out.println("the patient name is :"+p.getPersonName());

                    //Person person = (Person) selectPatComboBox.getSelectedItem();
                    VitalSign vs = (VitalSign) jTable1.getValueAt(selectedRow, 0);

                    vs.setRespRate(rrate);
                    vs.setHeartRate(hrate);
                    vs.setBloodPressure(bp);
                    vs.setWeight(wt);
                    vs.getTimestamp();

                    populateTable();

                    //Display success message
                    JOptionPane.showMessageDialog(null, "Vital Sign sucessfully updated", "Add Success", JOptionPane.INFORMATION_MESSAGE);
                    resetFields();
                } else {
                    JOptionPane.showMessageDialog(null, "Enter a valid input", "Invalid Input", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Only numbers accepted.Please enter valid values", "Invalid input", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnSaveActionPerformed
        editPermission(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnViewDetails;
    private javax.swing.JTextField TxtAge;
    private javax.swing.JTextField TxtPatID;
    private javax.swing.JTextField TxtRespRate;
    private javax.swing.JTextField Txtbp;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblbp;
    private javax.swing.JLabel lblhrate;
    private javax.swing.JLabel lblresprate;
    private javax.swing.JLabel lblts;
    private javax.swing.JLabel lblwt;
    private javax.swing.JComboBox selectPatComboBox;
    private javax.swing.JTextField txtTimestamp;
    private javax.swing.JTextField txtWT;
    private javax.swing.JTextField txthrate;
    // End of variables declaration//GEN-END:variables
}
