/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.Drug;
import business.DrugCatalog;
import business.DrugItem;
import business.Store;
import business.StoreDirectory;
import initialization.Product;
import initialization.SupplierDirectory;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author SONY
 */
public class ManageInventory extends javax.swing.JPanel {

    /**
     * Creates new form ManageInventory
     */
    private JPanel userProcessContainer;
    private DrugCatalog drugCatalog;
    private StoreDirectory storeDirectory;

    public ManageInventory(JPanel userProcessContainer, DrugCatalog drugC, StoreDirectory storeDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        drugCatalog = drugC;
        storeDirectory = storeDir;
        
          

        for (Drug d : drugCatalog.getDrugList()) {
        //    System.out.println(d.getDrugName());
            drugComboBox.addItem(d);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    
//   // @Override
//    public Component prepareRenderer(TableCellRenderer renderer, int row, int col) {
//        Component comp = prepareRenderer(renderer, row, 1);
//        Object value = jTable1.getModel().getValueAt(row, 1);
//          //  Object value = getModel().getValueAt(row, col);
//    if (value.equals(false)) {
//        comp.setBackground(Color.red);
//    }else {
//       comp.setBackground(Color.white);
//    }
//    return comp;
//    }

    
    
    
    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
             
        int rowCount = dtm.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        Drug d = (Drug) drugComboBox.getSelectedItem();

        for (Store s : storeDirectory.getStoreList()) {
            for (DrugItem dI : s.getDrugInventory().getDrugInventory()) {
                if (d.getDrugName().equals(dI.getDrug().getDrugName())) {
                    jTable1.setForeground(Color.black);
                    Object[] row = new Object[2];
                    row[0] = s;
                    int quant = Integer.parseInt(dI.getQuantity());

                    if (quant <= 5) {
                       //txtColor();
                       row[1] = quant;
                    } else {
                       
                        row[1] = dI.getQuantity();
                        //txtColor();
                  
                    }
                    dtm.addRow(row);
                }
            }
        }
    }
    
//    
//    public void txtColor(){
//        jTable1.setForeground(Color.red);        
//    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drugComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        drugComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugComboBoxActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Store ID", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Select Drug from Catalog");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drugComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void drugComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugComboBoxActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_drugComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox drugComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
