/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StateAdminWorkArea;

import Business.Country.Country;
import Business.EcoSystem;
import Business.Employee.EmployeeDirectory;
import Business.State.State;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.UpdatePassswordJPanel;

/**
 *
 * @author SONY
 */
public class StateAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount account;
    private State state;
    private EmployeeDirectory personList;

    public StateAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;

        for (Country c : system.getCountryList()) {
            for (State s : c.getStateList().getStateList()) {
                for (UserAccount ua : s.getUserAccountDirectory().getUserAccountList()) {
                    if (ua.getUsername().equals(account.getUsername())) {
                        state = s;
                        personList = c.getEmployeeDirectory();
                    }
                }
            }

        }
        lblStateName.setText(account.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageStatejButton = new javax.swing.JButton();
        ManageStateAdminjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblStateName = new javax.swing.JLabel();
        btnUpdatePassword = new javax.swing.JButton();

        ManageStatejButton.setText("Manage Cities");
        ManageStatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageStatejButtonActionPerformed(evt);
            }
        });

        ManageStateAdminjButton.setText("Manage City Admin");
        ManageStateAdminjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageStateAdminjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel1.setText("State Admin Work Area");

        lblStateName.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblStateName.setText("<State>");

        btnUpdatePassword.setText("Update Password");
        btnUpdatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblStateName)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ManageStatejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageStateAdminjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(btnUpdatePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblStateName))
                .addGap(48, 48, 48)
                .addComponent(ManageStatejButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ManageStateAdminjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdatePassword)
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManageStatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageStatejButtonActionPerformed
        // TODO add your handling code here:
        ManageCityJPanel manageStateJPanel = new ManageCityJPanel(userProcessContainer, state, account);
        userProcessContainer.add("ManageStateJPanel", manageStateJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageStatejButtonActionPerformed

    private void ManageStateAdminjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageStateAdminjButtonActionPerformed
        // TODO add your handling code here:
        ManageCityAdminJPanel manageStateAdminJPanel = new ManageCityAdminJPanel(userProcessContainer, state, account);
        userProcessContainer.add("ManageStateAdminJPanel", manageStateAdminJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageStateAdminjButtonActionPerformed

    private void btnUpdatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePasswordActionPerformed
        // TODO add your handling code here:
        UpdatePassswordJPanel updatePassswordJPanel = new UpdatePassswordJPanel(userProcessContainer,account);
        userProcessContainer.add("manageOrganizationJPanel", updatePassswordJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUpdatePasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageStateAdminjButton;
    private javax.swing.JButton ManageStatejButton;
    private javax.swing.JButton btnUpdatePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStateName;
    // End of variables declaration//GEN-END:variables
}
