/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.BusinessIntelligence;

/**
 *
 * @author SONY
 */
import business.Business;
import business.Customer;
import business.CustomerDirectory;
import business.Salesperson;
import java.util.Collections;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class CustomerSalesVolumeJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CustomerDirectory customerDirectory;
    private Business business;

    /**
     * Creates new form CustomerSalesVolumeJPanel
     */
    public CustomerSalesVolumeJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.customerDirectory = business.getCustomerDirectory();
        Collections.sort(customerDirectory.getCustomerDirectory());
        populateTable();
        
    }
    
    public void populateTable(){
        
        DefaultTableModel dtm = (DefaultTableModel)customerTable.getModel();
        dtm.setRowCount(0);

        for (Customer customer : customerDirectory.getCustomerDirectory() ) {
            Object row[] = new Object[2];
            row[0] = customer;
            row[1] = customer.getTotalPurchases();
            
            dtm.addRow(row);

        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtMost = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Sales Volume"
            }
        ));
        jScrollPane1.setViewportView(customerTable);

        jButton1.setText("Know the best Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel1.setText("Customer Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMost, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMost))
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int maxTot = 0;
        int maxPID = 0;
        String maxPName = "";
        for (Customer cust : customerDirectory.getCustomerDirectory()){
            if (cust.getTotalPurchases() > maxTot) {
                maxTot = cust.getTotalPurchases();
                maxPID = cust.getCustomerID();
                maxPName = cust.getCustomerName();
            }
        }
      //  System.out.println("The most popular product is : " + maxPID + " with sales volume :" + maxTot);
        txtMost.setText(maxPName);
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customerTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMost;
    // End of variables declaration//GEN-END:variables
}
