/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.BusinessIntelligence;

import business.Business;
import business.MasterOrderCatalog;
import business.Order;
import business.OrderItem;
import business.Product;
import business.ProductCatalog;
import business.Salesperson;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SONY
 */
public class PopularProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PopularProductJPanel
     */
    private JPanel userProcessContainer;
    private MasterOrderCatalog masterOrderCatalog;
    private Business business;
    private ProductCatalog productCatalog;

    public PopularProductJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.masterOrderCatalog = business.getMasterOrderCatalog();
        productCatalog = business.getProductCatalog();

        for (Product p : productCatalog.getProductcatalog()) {

            p.setTotSale(0);
            for (Order order : masterOrderCatalog.getOrderCatalog()) {
                for (OrderItem oi : order.getOrderItemList()) {

                    if (oi.getProduct().getProductID() == p.getProductID()) {
                        int popProd = oi.getQuantity();
                        p.setTotSale(popProd + p.getTotSale());

                    }
                }
            }

        }

        populateTable();
    }

    public void populateTable() {

        DefaultTableModel dtm = (DefaultTableModel) salesTable.getModel();
        dtm.setRowCount(0);

        for (Product p : productCatalog.getProductcatalog()) {
            Object row[] = new Object[2];
            row[0] = p;
            row[1] = p.getTotSale();

            dtm.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnMost = new javax.swing.JButton();
        txtMostPop = new javax.swing.JTextField();

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Total Sales"
            }
        ));
        jScrollPane1.setViewportView(salesTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel1.setText("Popular Product");

        btnMost.setText("Most Popular  Product");
        btnMost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnMost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMostPop, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMost)
                    .addComponent(txtMostPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostActionPerformed
        // TODO add your handling code here:
        int maxTot = 0;
        int maxPID = 0;
        String maxPName = "";
        for (Product p : productCatalog.getProductcatalog()) {
            if (p.getTotSale() > maxTot) {
                maxTot = p.getTotSale();
                maxPID = p.getProductID();
                maxPName = p.getProdName();
            }
        }
        System.out.println("The most popular product is : " + maxPID + " with sales volume :" + maxTot);
        txtMostPop.setText(maxPName);
    }//GEN-LAST:event_btnMostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable salesTable;
    private javax.swing.JTextField txtMostPop;
    // End of variables declaration//GEN-END:variables
}
