/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.BusinessIntelligence;

import business.SalesPersonDirectory;
import business.Salesperson;
import java.util.Collections;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SONY
 */
public class SalesVolumeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesVolumeJPanel
     */
    
    private JPanel userProcessContainer;
    private SalesPersonDirectory salesPersonDirectory;
    
    public SalesVolumeJPanel(JPanel userProcessContainer,SalesPersonDirectory salesPersonDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.salesPersonDirectory = salesPersonDirectory;
        Collections.sort(salesPersonDirectory.getSalesPersonDirectory());
        populateTable(); 
    }

    
    public void populateTable(){
        
        DefaultTableModel dtm = (DefaultTableModel)salesVolumeTable.getModel();
        dtm.setRowCount(0);

        for (Salesperson salesperson : salesPersonDirectory.getSalesPersonDirectory()) {
            Object row[] = new Object[3];
            row[0] = salesperson;
            row[1] = salesperson.getPersonName();
            row[2] = salesperson.getSalesVolume();
            dtm.addRow(row);

        }
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesVolumeTable = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel1.setText("Top 3 Salesperson and their Sales Volume");

        salesVolumeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sales ID", "Name", "Sales Volumel"
            }
        ));
        jScrollPane1.setViewportView(salesVolumeTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable salesVolumeTable;
    // End of variables declaration//GEN-END:variables
}
