/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.BusinessIntelligence;

import business.Business;
import business.MasterOrderCatalog;
import business.Order;
import business.OrderItem;
import business.SalesPersonDirectory;
import business.Salesperson;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SONY
 */
public class TargetMetJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SalesPersonDirectory salesPersonDirectory;
    private MasterOrderCatalog masterOrderCatalog;
    private Business business;

    /**
     * Creates new form TargetMetJPanel
     */
    public TargetMetJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.salesPersonDirectory = business.getSalesPersonDirectory();
        this.masterOrderCatalog = business.getMasterOrderCatalog();
        this.business = business;

        for (Salesperson s : salesPersonDirectory.getSalesPersonDirectory()) {
            s.setBelowTarget(0);
            s.setAboveTarget(0);
            for (Order o : masterOrderCatalog.getOrderCatalog()) {
                if (o.getSalesperson().getSalesID() == s.getSalesID()) {
                    int abt = s.getAboveTarget();
                    int bet = s.getBelowTarget();
                    for (OrderItem oi : o.getOrderItemList()) {
                        if (oi.getSalesprice() > oi.getProduct().getPrice()) {
                            s.setAboveTarget(abt + oi.getQuantity());
                        } else if (oi.getSalesprice() < oi.getProduct().getPrice()) {
                            s.setBelowTarget(bet + oi.getQuantity());
                        }

                    }

                }
            }
        }

        populateAboveTable();
        populateBelowTable();

    }

    public void populateAboveTable() {
        DefaultTableModel dtm = (DefaultTableModel) aboveTargetTable.getModel();
        dtm.setRowCount(0);

        for (Salesperson salesperson : salesPersonDirectory.getSalesPersonDirectory()) {
            Object row[] = new Object[3];
            row[0] = salesperson;
            row[1] = salesperson.getPersonName();
            row[2] = salesperson.getAboveTarget();

            dtm.addRow(row);

        }
    }

    public void populateBelowTable() {
        DefaultTableModel dtm = (DefaultTableModel) belowTargetTable.getModel();
        dtm.setRowCount(0);

        for (Salesperson salesperson : salesPersonDirectory.getSalesPersonDirectory()) {
            Object row[] = new Object[3];
            row[0] = salesperson;
            row[1] = salesperson.getPersonName();
            row[2] = salesperson.getBelowTarget();

            dtm.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        belowTargetTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        aboveTargetTable = new javax.swing.JTable();

        belowTargetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sales ID", "Salesperson ", "No. of Products"
            }
        ));
        jScrollPane1.setViewportView(belowTargetTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel1.setText("Below Target Sales");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("Above Target Sales");

        aboveTargetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sales ID", "Salesperson ", "No. of Products"
            }
        ));
        jScrollPane2.setViewportView(aboveTargetTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable aboveTargetTable;
    private javax.swing.JTable belowTargetTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
