/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import Business.Person;



/**
 *
 * @author SONY
 */
public class ViewJPanel extends javax.swing.JPanel {
private Person p1 = new Person();
    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(Person p1) {
        initComponents();
        this.p1 = p1;
        displayValues(p1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewlblOcc = new javax.swing.JLabel();
        ViewlblEmail = new javax.swing.JLabel();
        ViewtxtareaStreetAdd = new javax.swing.JScrollPane();
        ViewTxtareaStAdd = new javax.swing.JTextArea();
        ViewlblareaCode = new javax.swing.JLabel();
        ViewtxtTown = new javax.swing.JTextField();
        ViewlblFname = new javax.swing.JLabel();
        ViewlblPhone = new javax.swing.JLabel();
        ViewtxtZip = new javax.swing.JTextField();
        ViewlblLname = new javax.swing.JLabel();
        ViewtxtFname = new javax.swing.JTextField();
        ViewlblMName = new javax.swing.JLabel();
        ViewlblDOB = new javax.swing.JLabel();
        ViewtxtOcc = new javax.swing.JTextField();
        ViewtxtEmail = new javax.swing.JTextField();
        ViewlblAdd = new javax.swing.JLabel();
        ViewtxtLname = new javax.swing.JTextField();
        ViewtxtArea = new javax.swing.JTextField();
        ViewlblTown = new javax.swing.JLabel();
        ViewtxtMname = new javax.swing.JTextField();
        ViewtxtPhone = new javax.swing.JTextField();
        ViewlblZip = new javax.swing.JLabel();
        ViewtxtDOB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        ViewlblOcc.setText("Occupation");

        ViewlblEmail.setText("Email Address");

        ViewTxtareaStAdd.setEditable(false);
        ViewTxtareaStAdd.setColumns(20);
        ViewTxtareaStAdd.setRows(5);
        ViewtxtareaStreetAdd.setViewportView(ViewTxtareaStAdd);

        ViewlblareaCode.setText("Area code");

        ViewtxtTown.setEditable(false);
        ViewtxtTown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewtxtTownActionPerformed(evt);
            }
        });

        ViewlblFname.setText("First Name");

        ViewlblPhone.setText("Phone number");

        ViewtxtZip.setEditable(false);

        ViewlblLname.setText("Last Name");

        ViewtxtFname.setEditable(false);
        ViewtxtFname.setToolTipText("Enter First Name");
        ViewtxtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewtxtFnameActionPerformed(evt);
            }
        });

        ViewlblMName.setText("Middle Name");

        ViewlblDOB.setText("Date of Birth");

        ViewtxtOcc.setEditable(false);

        ViewtxtEmail.setEditable(false);

        ViewlblAdd.setText("Street Address");

        ViewtxtLname.setEditable(false);
        ViewtxtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewtxtLnameActionPerformed(evt);
            }
        });

        ViewtxtArea.setEditable(false);

        ViewlblTown.setText("Town");

        ViewtxtMname.setEditable(false);

        ViewtxtPhone.setEditable(false);

        ViewlblZip.setText("Zip Code");

        ViewtxtDOB.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewlblFname)
                            .addComponent(ViewlblLname)
                            .addComponent(ViewlblMName)
                            .addComponent(ViewlblDOB)
                            .addComponent(ViewlblZip)
                            .addComponent(ViewlblTown)
                            .addComponent(ViewlblareaCode)
                            .addComponent(ViewlblOcc)
                            .addComponent(ViewlblAdd)
                            .addComponent(ViewlblPhone)
                            .addComponent(ViewlblEmail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ViewtxtMname)
                            .addComponent(ViewtxtLname)
                            .addComponent(ViewtxtFname)
                            .addComponent(ViewtxtDOB)
                            .addComponent(ViewtxtareaStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(ViewtxtTown)
                            .addComponent(ViewtxtZip)
                            .addComponent(ViewtxtOcc)
                            .addComponent(ViewtxtEmail)
                            .addComponent(ViewtxtArea)
                            .addComponent(ViewtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewtxtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewlblFname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewlblLname)
                    .addComponent(ViewtxtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewlblMName)
                    .addComponent(ViewtxtMname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewtxtareaStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewlblAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ViewlblDOB)
                    .addComponent(ViewtxtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewlblTown, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ViewtxtTown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewlblZip)
                    .addComponent(ViewtxtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewtxtOcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewlblOcc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewlblEmail)
                    .addComponent(ViewtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewlblareaCode)
                    .addComponent(ViewtxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewlblPhone)
                    .addComponent(ViewtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewtxtTownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewtxtTownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewtxtTownActionPerformed

    private void displayValues(Person p1){
     ViewtxtFname.setText(p1.getFirstName());
     ViewtxtLname.setText(p1.getLastName());
     ViewtxtMname.setText(p1.getMiddleName());
     ViewtxtDOB.setText(p1.getDate());
     ViewtxtArea.setText(p1.getAreaCode());
     ViewtxtEmail.setText(p1.getEmailID());
     ViewtxtTown.setText(p1.getTown());
     ViewtxtZip.setText(p1.getZipCode());
     ViewtxtPhone.setText(p1.getPhone());
     ViewtxtOcc.setText(p1.getOccupation());
     ViewTxtareaStAdd.setText(p1.getStreetAdd());
    }
    private void ViewtxtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewtxtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewtxtFnameActionPerformed

    private void ViewtxtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewtxtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewtxtLnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ViewTxtareaStAdd;
    private javax.swing.JLabel ViewlblAdd;
    private javax.swing.JLabel ViewlblDOB;
    private javax.swing.JLabel ViewlblEmail;
    private javax.swing.JLabel ViewlblFname;
    private javax.swing.JLabel ViewlblLname;
    private javax.swing.JLabel ViewlblMName;
    private javax.swing.JLabel ViewlblOcc;
    private javax.swing.JLabel ViewlblPhone;
    private javax.swing.JLabel ViewlblTown;
    private javax.swing.JLabel ViewlblZip;
    private javax.swing.JLabel ViewlblareaCode;
    private javax.swing.JTextField ViewtxtArea;
    private javax.swing.JTextField ViewtxtDOB;
    private javax.swing.JTextField ViewtxtEmail;
    private javax.swing.JTextField ViewtxtFname;
    private javax.swing.JTextField ViewtxtLname;
    private javax.swing.JTextField ViewtxtMname;
    private javax.swing.JTextField ViewtxtOcc;
    private javax.swing.JTextField ViewtxtPhone;
    private javax.swing.JTextField ViewtxtTown;
    private javax.swing.JTextField ViewtxtZip;
    private javax.swing.JScrollPane ViewtxtareaStreetAdd;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
